# -*- coding: utf-8 -*-
"""tweet scrapper

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_Z59VxVKAL3pHdniVSvuT7_OTQacxpQ
"""

import tweepy

# API Key: Q2RsEqlaSBEQK8QDChDUNxxmz
# API Secret Key: Nbw2VqOGfVUX0gyJGsT5c96RbglWqEdFrgF4h7WUUfUMTjoXl6
# Access Token: 1486419199413174272-KpXEGGkJcVrtqNLYo5xUtAPKX62Gch
# Access Secret Token: TUxRgI4xWx5bNn5RUaVc1ca7HVKsw1MkBVA14qWxKC3Kk

consumer_key = "Q2RsEqlaSBEQK8QDChDUNxxmz"
consumer_secret = "Nbw2VqOGfVUX0gyJGsT5c96RbglWqEdFrgF4h7WUUfUMTjoXl6"
access_token = "1486419199413174272-KpXEGGkJcVrtqNLYo5xUtAPKX62Gch"
access_token_secret = "TUxRgI4xWx5bNn5RUaVc1ca7HVKsw1MkBVA14qWxKC3Kk"

#Establish Connection to Twitter API

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True)

#Hashtag used for scrapping tweets

hashtag = "#climatechange -filter:retweets"

#list to store the tweets

tweets_list = []

#Scrapping Tweets based on hashtag

tweets_by_hashtag = tweepy.Cursor(api.search_tweets, q=hashtag, lang='en').items(500)
print("Tweets Scrapped Successfully!")

#Pulling and information from tweets and loading to the list using iterator object

for tweet in tweets_by_hashtag:
    '''
    tweet_id = tweet.id
    user_id = tweet.user.id
    tweeted_by = tweet.user.name
    tweet_content = str(tweet.text)
    no_of_retweets = tweet.retweet_count
    no_of_favourites = tweet.favorite_count
    '''
    tweets_list.append([str(tweet.text), tweet.id])

#Creating Seperate List with Headers for storing tweets in a JSON File

tweets_list_for_json = ["message", "tweet_id"]

#Adding the tweets to the JSON Tweet List

tweets_list_for_json.extend(tweets_list)

#print(tweets_list_for_json)

import json

#Exporting the Tweets scrapped to JSON Format

json_tweets=json.dumps(tweets_list_for_json)

print(json_tweets)

#Using Pandas library to report statisctics

import pandas as pd

headers = ["message", "tweet_id"]

#Import tweets to a pandas dataframe

tweets_df = pd.DataFrame(tweets_list,columns=headers)

tweets_df

tweets_df.to_csv('manual.csv', index = False)